### PR TITLE
Allow using listed apps as blacklist

### PR DESCRIPTION
**Pull request by floschliep**
Personally, I'd rather have cmd+Q working for all apps with a few exceptions. Therefore I implemented functionality that allows the list of apps to be used as either a whitelist or blacklist.

Thanks for your work, let me know what you think about my proposed changes.

### CODE REVIEW

**Comment by steve228uk** [comment]
Hey @floschliep, this is awesome work! Thanks so much.

Two things:

1. The `ListMode.swift` file isn't currently included in the Xcode project. Might be worth just dragging that into the Exclude Apps group.
2. I'm not sure the wording around Blacklist/Whitelist is clear. For me, a blacklist will be apps that QBlocker ignores and a whitelist will be apps that QBlocker with block. Perhaps we should change the UI to a popup button with "Don't use QBlocker" and "Only use QBlocker" as options…

screen shot 2016-05-25 at 14 49 59

Let me know your thoughts!

💯 🚀

**Comment by floschliep** [comment]
`ListMode.swift` isn't included in the project file I pushed to GitHub because I messed with the project settings. CocoaPods didn't work for me (it can't find `RealmSwift`) so I just added `DevMateKit` and `RealmSwift` manually and created a copy files build phase. I didn't want to break your setup so I only committed the code changes.

You're totally right about the popup button, this will work much better. What would you label the menu item to open the window then? Perhaps *Excluded Apps* and *Included Apps* respectively?

**Comment by steve228uk** [comment]
Ah no problem, I can manually add that after merge. 

Let's go with "Preferences…". That gives us scope to add #2 to the panel at a later date.

**Comment by floschliep** [comment]
I implemented the changes, please take a look at https://github.com/steve228uk/QBlocker/pull/14/commits/3d55831a73327fce592619fc1091bf0586db336b.

I changed the way the preferences window controller is being presented because I noticed the storyboard segue would create a new controller each time but never release it. Let me know if that's okay with you.

I reverted the changes on the project file and added `ListMode.swift` so everything should be fine now.

**Comment by steve228uk** [comment]
@floschliep Nice catch with the memory leak there! Looks like that also fixes #5.

Thanks so much for this PR. Merging now 👍 🚢

**Pull request merged**
